# Generated by Django 6.1 on 2026-08-20 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidade', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Van', 'Van'), ('Carro de passeio', 'Carro de passeio')], max_length=20)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='reservas.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('atividade', models.CharField(max_length=200)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('numero_passageiros', models.PositiveIntegerField()),
                ('data_hora_saida', models.DateTimeField()),
                ('data_hora_retorno', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.veiculo')),
            ],
        ),
    ]
