# Generated by Django 6.1 on 2026-08-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='codigo',
            field=models.CharField(default='VL-01', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
