# Generated by Django 6.1 on 2026-08-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_veiculo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('VL', 'Veículo Leve'), ('VC', 'Veículo Coletivo (Van)')], max_length=2),
        ),
    ]
